### ISSUE TITLE
Can't rebuild the project

### ISSUE THREAD

**Issue by ccamacho** [spekt8/spekt8#19]
Each time I run:

`
npm run-script build --loglevel verbose
`

To build the project I get this:

`
> webpack
Hash: e3bf32caefe7e505916a
Version: webpack 4.41.2
Time: 822ms
Built at: 2019-10-17 17:46:26
 1 asset
Entrypoint main = main.js
[0] ./src/index.js 302 bytes {0} [built] [failed] [1 error]
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (25:1)
  23 | 
  24 | ReactDOM.render(
> 25 | 	<MuiThemeProvider theme={theme}>
     | 	^
  26 | 		<Provider store={store}>
  27 | 			<App />
  28 | 		</Provider>
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.1 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
npm verb lifecycle docker-kubernetes-udemy3@1.0.0~build: unsafe-perm in lifecycle true
npm verb lifecycle docker-kubernetes-udemy3@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle docker-kubernetes-udemy3@1.0.0~build: CWD: /pystol-ui
npm info lifecycle docker-kubernetes-udemy3@1.0.0~build: Failed to exec build script
npm verb stack Error: docker-kubernetes-udemy3@1.0.0 build: `webpack`
npm verb stack Exit status 2
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:915:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid docker-kubernetes-udemy3@1.0.0
npm verb cwd /pystol-ui
npm verb Linux 3.10.0-123.el7.x86_64
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "build" "--loglevel" "verbose"
npm verb node v8.16.2
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! docker-kubernetes-udemy3@1.0.0 build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the docker-kubernetes-udemy3@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 2, true ]
npm timing npm Completed in 2044ms
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-17T17_46_26_869Z-debug.log
 ---> 3c8d036b342b
Removing intermediate container e113d2784172
Step 7/9 : RUN file="$(ls -1 /root/.npm/_logs)" && cat "/root/.npm/_logs/$file"
 ---> Running in 513064ebd76a
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'build',
1 verbose cli   '--loglevel',
1 verbose cli   'verbose' ]
2 info using npm@6.4.1
3 info using node@v8.16.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle docker-kubernetes-udemy3@1.0.0~prebuild: docker-kubernetes-udemy3@1.0.0
6 info lifecycle docker-kubernetes-udemy3@1.0.0~build: docker-kubernetes-udemy3@1.0.0
7 verbose lifecycle docker-kubernetes-udemy3@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle docker-kubernetes-udemy3@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/pystol-ui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle docker-kubernetes-udemy3@1.0.0~build: CWD: /folder
10 silly lifecycle docker-kubernetes-udemy3@1.0.0~build: Args: [ '-c', 'webpack' ]
11 silly lifecycle docker-kubernetes-udemy3@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle docker-kubernetes-udemy3@1.0.0~build: Failed to exec build script
13 verbose stack Error: docker-kubernetes-udemy3@1.0.0 build: `webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid docker-kubernetes-udemy3@1.0.0
15 verbose cwd /folder
16 verbose Linux 3.10.0-123.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "build" "--loglevel" "verbose"
18 verbose node v8.16.2
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error docker-kubernetes-udemy3@1.0.0 build: `webpack`
22 error Exit status 2
23 error Failed at the docker-kubernetes-udemy3@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
 ---> 419e7929209c
Removing intermediate container 513064ebd76a
Step 8/9 : EXPOSE 3000
 ---> Running in 0dfcc42f157e
 ---> cebf07c34b0b
Removing intermediate container 0dfcc42f157e
Step 9/9 : CMD npm run server --loglevel verbose
 ---> Running in bdb7f3e56c3a
 ---> f682739bbb9b
Removing intermediate container bdb7f3e56c3a
Successfully built f682739bbb9b
`

Do you know what can be wrong?

**Comment by ccamacho** [comment]
removed .babelrc by mistake
